version: "3.3"
services:
  db:
    image: mariadb:latest
    volumes:
      - "/.db_data:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - default

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_TABLE_PREFIX: "wp_"
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: define('WP_DEFAULT_THEME', 'apnic');
    volumes:
      - "./wp_data:/var/www/html/wp-content"
      - "./php.ini:/usr/local/etc/php/conf.d/docker-php-php.ini"
    networks:
      - default

volumes:
  db_data:
  wp_data:

networks:
  default:
